version: "3"
services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports: 
      - '82:3000'
    labels: 
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.nightfall.rule=Host(`nightfall.riou.pro`)"
      - "traefik.http.routers.nightfall.entrypoints=web-secure"
      - "traefik.http.routers.nightfall.tls=true"
      - "traefik.http.routers.nightfall.tls.certresolver=ssl"
      - "traefik.http.routers.nightfall-http.rule=Host(`nightfall.riou.pro`)"
      - "traefik.http.routers.nightfall-http.entrypoints=web"
      - "traefik.http.middlewares.https.redirectscheme.scheme=https"
      - "traefik.http.routers.nightfall-http.middlewares=https@docker"
      - "traefik.port=3000"
  # links:
  #   - mongo  
  # mongo:
  #   image: mongo
  #   ports: 
  #     - '27017:27017'